version: '3.8'

services:
  db:
    image: postgres
    container_name: ejareii_pg
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ejareii
      POSTGRES_PASSWORD: a5fsergtete5ees23341
      POSTGRES_DB: rentals
    volumes:
      - ejareiipg:/var/lib/postgresql/data
  # redis:
  #   image: redis
  #   container_name: ejareii_redis
  #   ports:
  #     - "6380:6379"
  #   volumes:
  #     - ejareiiredis:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "13000:9000"
    depends_on:
      - db
    environment:
      DB_URL: "postgres://ejareii:a5fsergtete5ees23341@db/rentals"


volumes:
  ejareiipg:
  # pgdata:
  ejareiiredis:
