version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    restart: unless-stopped
